EXPECTED_CHARACTERS_FREQUENCY = {
    "\n": 1,
    " ": 93,
    ",": 11,
    ".": 5,
    ":": 3,
    ";": 3,
    "?": 2,
    "B": 1,
    "D": 2,
    "E": 1,
    "L": 2,
    "M": 1,
    "N": 1,
    "Q": 4,
    "R": 1,
    "T": 1,
    "a": 39,
    "b": 5,
    "c": 15,
    "d": 21,
    "e": 63,
    "f": 3,
    "g": 6,
    "h": 8,
    "i": 59,
    "l": 15,
    "m": 23,
    "n": 31,
    "o": 28,
    "p": 19,
    "q": 6,
    "r": 36,
    "s": 31,
    "t": 36,
    "u": 47,
    "v": 6,
}

EXPECTED_CHARACTERS_FREQUENCY_AS_PERCENTAGE_OF_TOTAL = {
    "\n": "0.16%",
    " ": "14.79%",
    ",": "1.75%",
    ".": "0.79%",
    ":": "0.48%",
    ";": "0.48%",
    "?": "0.32%",
    "B": "0.16%",
    "D": "0.32%",
    "E": "0.16%",
    "L": "0.32%",
    "M": "0.16%",
    "N": "0.16%",
    "Q": "0.64%",
    "R": "0.16%",
    "T": "0.16%",
    "a": "6.20%",
    "b": "0.79%",
    "c": "2.38%",
    "d": "3.34%",
    "e": "10.02%",
    "f": "0.48%",
    "g": "0.95%",
    "h": "1.27%",
    "i": "9.38%",
    "l": "2.38%",
    "m": "3.66%",
    "n": "4.93%",
    "o": "4.45%",
    "p": "3.02%",
    "q": "0.95%",
    "r": "5.72%",
    "s": "4.93%",
    "t": "5.72%",
    "u": "7.47%",
    "v": "0.95%",
}

EXPECTED_TOP_10_MOST_USED_WORDS = [
    "quod",
    "a",
    "non",
    "natura",
    "esse",
    "quae",
    "enim",
    "sunt",
    "vero",
    "puto",
]

EXPECTED_REVERSED_TEXT_WITH_SAVED_WORDS = "dicemus? esse datum nihil natura a praecipue praestat, plurimum animantibus ceteris qui homini, Et huc? inquit, tu, Quid solemus: congressu in quae illa, prima Deinde referas; corpus ad quod habes, iam enim Nihil puto. iudicium nullum vero Bestiarum puto. fratri item quod sunt, probata valde ista vero Mihi Lucius: Tum interrete. constructio Reges: Duo desidero. elegantiora te a autem ego sunt, popularia protulisti, adhuc enim Quae peti; gerendae rei principia se a vivendi, beate finem aliunde verum esse non responderit iure natura Quibus elit. adipiscing consectetur amet, sit dolor ipsum Lorem reprehendo; non equidem Quod"

EXPECTED_REVERSED_TEXT = "?sumecid esse mutad lihin arutan a eupicearp ,tatsearp mumirulp subitnamina siretec iuq ,inimoh tE ?cuh ,tiuqni ,ut diuQ :sumelos ussergnoc ni eauq ,alli amirp ednieD ;sarefer suproc da douq ,sebah mai mine lihiN .otup muicidui mullun orev muraitseB .otup irtarf meti douq ,tnus ataborp edlav atsi orev ihiM :suicuL muT .eterretni oitcurtsnoc :segeR ouD .oredised aroitnagele et a metua oge ,tnus airalupop ,itsilutorp cuhda mine eauQ ;itep eadnereg ier aipicnirp es a ,idneviv etaeb menif ednuila murev esse non tirednopser erui arutan subiuQ .tile gnicsipida rutetcesnoc ,tema tis rolod muspi meroL\n;odneherper non mediuqe douQ"

EXPECTED_TEXT_WITHOUT_SPACES_AND_PUNCTUATION = "QuodequidemnonreprehendoLoremipsumdolorsitametconsecteturadipiscingelitQuibusnaturaiureresponderitnonesseverumaliundefinembeatevivendiaseprincipiareigerendaepetiQuaeenimadhucprotulistipopulariasuntegoautemateelegantioradesideroDuoRegesconstructiointerreteTumLuciusMihiveroistavaldeprobatasuntquoditemfratriputoBestiarumveronullumiudiciumputoNihilenimiamhabesquodadcorpusreferasDeindeprimaillaquaeincongressusolemusQuidtuinquithucEthominiquiceterisanimantibusplurimumpraestatpraecipueanaturanihildatumessedicemus"

EXPECTED_TEN_LONGEST_SENTENCES = [
    "Quibus natura iure responderit non esse verum aliunde finem beate vivendi, a se principia rei gerendae peti; Quae enim adhuc protulisti, popularia sunt, ego autem a te elegantiora desidero.",
    "Nihil enim iam habes, quod ad corpus referas; Deinde prima illa, quae in congressu solemus: Quid tu, inquit, huc?",
    "Et homini, qui ceteris animantibus plurimum praestat, praecipue a natura nihil datum esse dicemus?",
    "Quod equidem non reprehendo;\nLorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "Tum Lucius: Mihi vero ista valde probata sunt, quod item fratri puto.",
    "Bestiarum vero nullum iudicium puto.",
    "Duo Reges: constructio interrete.",
]

EXPECTED_TEN_SHORTEST_SENTENCES = [
    "Duo Reges: constructio interrete.",
    "Bestiarum vero nullum iudicium puto.",
    "Tum Lucius: Mihi vero ista valde probata sunt, quod item fratri puto.",
    "Quod equidem non reprehendo;\nLorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "Et homini, qui ceteris animantibus plurimum praestat, praecipue a natura nihil datum esse dicemus?",
    "Nihil enim iam habes, quod ad corpus referas; Deinde prima illa, quae in congressu solemus: Quid tu, inquit, huc?",
    "Quibus natura iure responderit non esse verum aliunde finem beate vivendi, a se principia rei gerendae peti; Quae enim adhuc protulisti, popularia sunt, ego autem a te elegantiora desidero.",
]
